version: '3.7'

services:

  solongo:
    container_name: solongo
    hostname: solongo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/code'
      - '/code/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true